#1EJERCICIO(mayor de tres números)


*   Método clásico






In [ ]:
var1=int(input("ingresar el valor de la 1° variable:"))
var2=int(input("ingresar el valor de la 2° variable:"))
var3=int(input("ingresar el valor de la 3° variable:"))
if (var1>var2 and var1>var3):
  print("el mayor es :"+str(var1))
elif (var2>var1 and var2>var3):
  print("el mayor es :"+str(var2))
else:
  print("el mayor es :"+str(var3))




*  Método Python



In [ ]:
var1, var2,var3= input ("Ingrese los tres números separados por coma:").split(",")
print("El número máximo es: "+ str(max(var1,var2,var3)))




---
#2EJERCICIO(Suma)
*   Método clásico




In [ ]:
tot=int(input("Ingrese la cantidad N de números: "))
suma=0
for i in range(0, tot):
  suma+=int(input("ingrese el valor del num "+str(i)+": "))
  print("El total es: "+str(suma))


*   Método minimalista python



In [ ]:
for i in range(0, int(input("Ingrese la cantidad N de números: "))):
  suma+=int(input("ingrese el valor del num "+str(i)+": "))
  print("El total es: "+str(suma))



---
#3EJERCICIO(par entre números)
*   Método clásico




In [ ]:
inicio=int(input("Número minimo: "))
fin=int(input("Número final: "))
for i in range(inicio,fin):
  if ((i%2)==0):
    print("El número par :" + str(i))

*   Método minimalista python



In [ ]:
for i in range(int(input("Número minimo: ")),int(input("Número final: "))):
  if( (i%2)==0 ): print("El número par :" + str(i))



---
#4EJERCICIO(imprimir listas)
*   Método clásico



In [ ]:
rango1=list(range(1,13))
rango2=list(range(12,0,-1))
print(rango1+rango2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


* Método minimalista python


In [ ]:
lista=list(range(1,12))
print(lista+lista[::-1])

[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9]


#5EJERCICIO(números aleatorios)
* Método clásico

In [ ]:
##generación de números aleatorios.
import random
Var1= random.randrange(101)
print(Var1)


In [ ]:
import random
lista= [ random.randrange(20,22) for i in range(10)]
print(lista)


[21, 21, 20, 20, 20, 20, 20, 21, 20, 21]


* Método minimalista python

In [ ]:
for i in range(10): print(random.randrange(100))

---
#6EJERCICIO(población y edades)
* Método planteado



In [ ]:
import random
habitantes=random.randint(1,15)
mayores=0
lista= [random.randrange(30) for i in range(habitantes)]
for i in lista: 
 if(i>=18 ):mayores+=1
print("La población total es de:"+str(habitantes)+"\nporcentaje de mayores:"+str((mayores*100)/habitantes)+"porcentaje de menores"+ str(((habitantes-mayores)*100)/habitantes))

#7EJERCICIO(numpy candidatos alcaldía)
* Método python


In [ ]:
import numpy as np
from random import randint
matriz = np.array([[i+1,randint(1,20000)] for i in range(6)])
ganador = np.where(matriz[:,1] == matriz[:,1].max())
print("las votaciones:\n"+str(matriz)+"\n El ganador es: "+str(matriz[ganador[0]]))

#8EJERCICIO(numpy paridos políticos)
* Método python

In [ ]:
import numpy as np; from random import randint
votos_20xx = np.random.randint(3000,size=(123,6))
tot_votos = np.array([[candidato+1,votos_20xx[:,candidato].sum()] for candidato in range(len(votos_20xx[0]))])
ganador = np.where(tot_votos == tot_votos[:,1].max())
print("El candidato ganador fue el: "+str(tot_votos[ganador[0]])+"\n El total de votos por candidato es \n"+str(tot_votos))

#9EJERCICIO(formula uno)
* Método python

In [ ]:
import numpy as np
matriz = np.random.uniform(8.2,10,size=(4,5))
tot_vueltas = np.array([[corredor+1,matriz[:,corredor].sum()] for corredor in range(len(matriz[0]))])
ganador=np.where(matriz == matriz[:,1].min())
print ("Resultados de la carrera:\n"+str(matriz)+"\nEl Piloto ganador fue el: "+str(tot_vueltas[ganador[0]]))

Resultados de la carrera:
[[8.54960836 9.37461863 8.58562188 8.7314217  8.72412044]
 [8.35461075 9.81509476 9.17158833 8.30705655 8.43859492]
 [8.69719769 8.5639066  9.77147304 9.54350589 9.65718613]
 [9.36588105 9.68233681 9.99344786 8.48284015 9.09091702]]
El Piloto ganador fue el: [[ 3.         37.52213111]]
